{
    "openapi": "3.0.0",
    "info": {
        "title": "BlogAPI",
        "version": "1.0.0",
        "description": ""
    },
    "servers": [
        {
            "url": "http://127.0.0.1:8765/"
        }
    ],
    "paths": {
        "/blog/comments": {
            "get": {
                "tags": [
                    "comment"
                ],
                "responses": {
                    "default": {
                        "description": "Default response"
                    },
                    "200": {
                        "$ref": "#/components/responses/CommentsResponse"
                    }
                },
                "operationId": "getPosts",
                "summary": "Obtener todos los comentarios",
                "description": "Recurso para obtener todos los comentarios que están registradas actualmente"
            },
            "parameters": [
                {
                    "name": "rqUuid",
                    "description": "Identificador único (Ej: 208c9490)",
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 36
                    },
                    "in": "header",
                    "required": true
                }
            ]
        },
        "/blog/users": {
            "get": {
                "tags": [
                    "user"
                ],
                "responses": {
                    "200": {
                        "$ref": "#/components/responses/UsersResponse"
                    }
                },
                "operationId": "getUsers",
                "summary": "Obtener todos los usuarios",
                "description": "Recurso para obtener todos los usuarios que están registrados actualmente"
            },
            "parameters": [
                {
                    "name": "rqUuid",
                    "description": "Identificador único (Ej: 208c9490)",
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 36
                    },
                    "in": "header",
                    "required": true
                }
            ]
        },
        "/blog/tags": {
            "get": {
                "tags": [
                    "tag"
                ],
                "responses": {
                    "default": {
                        "description": "Default response"
                    },
                    "200": {
                        "$ref": "#/components/responses/TagsResponse"
                    }
                },
                "operationId": "getTopics",
                "summary": "Obtener todos las etiquetas",
                "description": "Recurso para obtener todas las etiquetas que están registradas actualmente"
            },
            "parameters": [
                {
                    "name": "rqUuid",
                    "description": "Identificador único (Ej: 208c9490)",
                    "schema": {
                        "type": "string",
                        "minLength": 1,
                        "maxLength": 36
                    },
                    "in": "header",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "user": {
                "title": "Root Type for user",
                "description": "Estructura con la información de un usuario",
                "type": "object",
                "properties": {
                    "user_uuid": {
                        "description": "UUID del usuario",
                        "type": "string"
                    },
                    "nickname": {
                        "description": "Nombre de usuario",
                        "type": "string"
                    },
                    "email": {
                        "description": "Dirección de correo del usuario",
                        "type": "string"
                    },
                    "signature": {
                        "description": "Firma del usuario",
                        "type": "string"
                    },
                    "registered_at": {
                        "description": "Fecha del registro",
                        "type": "string"
                    }
                },
                "example": {
                    "user_uuid": "a3b4632b-7655-49e1-a2db-b4a07627756c",
                    "nickname": "nickname",
                    "email": "email@mail.com",
                    "signature": "//\\(oo)/\\\\",
                    "registered_at": "2022-11-28T14:49:00.459Z"
                }
            },
            "tag": {
                "title": "Root Type for tag",
                "description": "Estructura con la información de una etiqueta",
                "type": "object",
                "properties": {
                    "key": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    }
                },
                "example": {
                    "key": "BOOK",
                    "description": "Libros"
                }
            },
            "comment": {
                "title": "Root Type for post",
                "description": "Estructura con la información de una publicación",
                "type": "object",
                "properties": {
                    "comment_uuid": {
                        "description": "UUID del comentario",
                        "type": "string"
                    },
                    "post_uuid": {
                        "description": "UUID de la publicación donde se hizo el comentario",
                        "type": "string"
                    },
                    "content": {
                        "description": "Contenido de la publicación",
                        "type": "string"
                    },
                    "published": {
                        "description": "Indica si el comentario se ha publicado o no",
                        "type": "boolean"
                    },
                    "created_at": {
                        "description": "Fecha en la que se creó el comentario",
                        "type": "string"
                    },
                    "published_at": {
                        "description": "Fecha en la que se publicó el comentario",
                        "type": "string"
                    }
                },
                "example": {
                    "comment_uuid": "3ec919a3-e14a-44d9-b20e-4a3f4bca060c",
                    "post_uuid": "25c0a9ab-013b-4093-b1b0-1e2d72fb9d9b",
                    "content": "Donec eu suscipit elit. Curabitur ut elit eu ligula hendrerit malesuada eget eget risus. Vestibulum ut efficitur nibh. Sed malesuada accumsan libero at aliquet. Donec in velit sit amet nunc pretium egestas",
                    "published": true,
                    "created_at": "2022-11-27T10:34:15.309259",
                    "published_at": "2022-11-28T14:49:00.459268"
                }
            }
        },
        "responses": {
            "UsersResponse": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/user"
                            }
                        },
                        "examples": {
                            "users_example": {
                                "value": [
                                    {
                                        "userUuid": "08139f8c-0a07-4064-bb2c-0ee3a9655736",
                                        "nickname": "erick_35",
                                        "email": "ee35@mail.com",
                                        "signature": "signature_1",
                                        "registeredAt": "2022-11-28T14:49:00.449699"
                                    },
                                    {
                                        "userUuid": "8731bf6c-ff6c-4cb2-b553-abf86fd02874",
                                        "nickname": "sergio_qrr",
                                        "email": "ser_1@mail.com",
                                        "signature": "signature_2",
                                        "registeredAt": "2021-01-18T04:19:50.449699"
                                    }
                                ]
                            }
                        }
                    }
                },
                "description": ""
            },
            "TagsResponse": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/tag"
                            }
                        },
                        "examples": {
                            "topics_example": {
                                "value": [
                                    {
                                        "key": "BOOK",
                                        "description": "Libros"
                                    },
                                    {
                                        "key": "REVIEW",
                                        "description": "Reseñas"
                                    }
                                ]
                            }
                        }
                    }
                },
                "description": ""
            },
            "CommentsResponse": {
                "content": {
                    "application/json": {
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/components/schemas/comment"
                            }
                        },
                        "examples": {
                            "comments_example": {
                                "value": [
                                    {
                                        "commentUuid": "3ec919a3-e14a-44d9-b20e-4a3f4bca060c",
                                        "postUuid": "25c0a9ab-013b-4093-b1b0-1e2d72fb9d9b",
                                        "content": "Sed malesuada accumsan libero at aliquet. Donec in velit sit amet nunc pretium egestas.",
                                        "published": true,
                                        "createdAt": "2022-11-28T14:49:00.459268",
                                        "publishedAt": "2022-11-28T14:49:00.459268"
                                    },
                                    {
                                        "commentUuid": "0ea8d85e-b484-4651-8995-c1f82ebc09fd",
                                        "postUuid": "25c0a9ab-013b-4093-b1b0-1e2d72fb9d9b",
                                        "content": "Donec eu suscipit elit. Curabitur ut elit eu ligula hendrerit malesuada eget eget risus. Vestibulum ut efficitur nibh. Sed malesuada accumsan libero at aliquet. Donec in velit sit amet nunc pretium egestas.",
                                        "published": false,
                                        "createdAt": "2022-11-28T14:49:00.460977"
                                    }
                                ]
                            }
                        }
                    }
                },
                "description": ""
            }
        }
    }
}